# -*- coding: utf-8 -*-
"""특정날_시간대_혼잡도_예측_지성.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwEgOb-yJpsESTFrNtCfuYW9EI_pQk6u
"""

# -*- coding: utf-8 -*-
import os
import glob
import sys
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

try:
    from IPython.display import display
except Exception:
    display = print

SAVE_FIGURES = True
GRAPH_DIR = Path("traffic_final_graphs_v5")
GRAPH_DPI = 240

# PPT에 그래프 이미지를 넣어 축소해도 설명 탭을 바로 읽을 수 있게
# 오른쪽 설명 박스와 하단 예측 기준 박스의 크기를 공통값으로 관리한다.
PPT_SIDE_BOX_FONT_SIZE = 12.2
PPT_BOTTOM_NOTE_FONT_SIZE = 12.4
PPT_BOX_PADDING = 0.72
PPT_BOX_LINEWIDTH = 1.35


# project_base는 Colab 업로드 확인 뒤 load_base_result()에서 연결한다.
pb = None


def _is_colab():
    try:
        import google.colab  # noqa: F401
        return True
    except Exception:
        return False


def maybe_upload_required_files():
    if not _is_colab():
        return

    from google.colab import files

    search_dirs = [Path("/content"), Path.cwd()]

    required_zip_name = "2020~2025 서울특별시 교통량 정제 데이터.zip"
    required_base_name = "project_base.py"

    def check_required_files():
        has_zip = any(
            glob.glob(str(d / "*2020~2025 서울특별시 교통량 정제 데이터*.zip"))
            for d in search_dirs
        )

        has_base = any(
            (d / "project_base.py").exists()
            for d in search_dirs
        )

        return has_zip, has_base

    while True:
        has_zip, has_base = check_required_files()

        if has_zip and has_base:
            print("필수 파일 확인 완료")
            print(f" - {required_zip_name}")
            print(f" - {required_base_name}")
            return

        print("\n필수 파일이 부족합니다.")
        print("아래 두 파일이 모두 있어야 실행을 시작합니다.")

        if not has_zip:
            print(f" - 필요: {required_zip_name}")
        else:
            print(f" - 확인됨: {required_zip_name}")

        if not has_base:
            print(f" - 필요: {required_base_name}")
        else:
            print(f" - 확인됨: {required_base_name}")

        print("\n업로드 창에서 필요한 파일을 모두 선택하세요.")
        uploaded = files.upload()

        if len(uploaded) == 0:
            raise FileNotFoundError(
                "필수 파일 업로드가 취소되었습니다. "
                "2020~2025 서울특별시 교통량 정제 데이터.zip과 project_base.py를 모두 업로드해야 합니다."
            )


def setup_paths():
    maybe_upload_required_files()

    for p in ["/content", os.getcwd()]:
        if p not in sys.path:
            sys.path.append(p)

    if Path("/content").exists():
        return "/content"

    return os.getcwd()


def set_korean_font():
    candidates = [
        "/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf",
        "/usr/share/fonts/truetype/nanum/NanumGothic.ttf",
    ]

    font_path = next((p for p in candidates if os.path.exists(p)), None)

    if font_path is None and _is_colab():
        subprocess.run(["apt-get", "-qq", "update"], check=False)
        subprocess.run(["apt-get", "-qq", "install", "-y", "fonts-nanum"], check=False)
        font_path = next((p for p in candidates if os.path.exists(p)), None)

    if font_path:
        fm.fontManager.addfont(font_path)
        font_name = fm.FontProperties(fname=font_path).get_name()
        plt.rc("font", family=font_name)
    else:
        plt.rc("font", family="DejaVu Sans")

    plt.rcParams["axes.unicode_minus"] = False
    plt.rcParams["figure.dpi"] = 145


def save_and_show(
    filename,
    bottom_note=None,
    bottom_margin=0.06,
    note_y=0.012,
    note_fontsize=PPT_BOTTOM_NOTE_FONT_SIZE,
    note_x=0.5,
    note_ha="center",
    note_linespacing=None,
    note_padding=None,
    note_linewidth=None,
    use_tight_layout=True,
):
    fig = plt.gcf()

    if bottom_note is not None:
        # PPT에 삽입하면 이미지가 축소되므로 설명문은 진한 색 + 굵은 글씨로 고정한다.
        note_color = globals().get("ALPHA_TEXT", "#111827")
        note_edge = globals().get("ALPHA_TEXT", "#111827")

        fig.text(
            note_x,
            note_y,
            bottom_note,
            ha=note_ha,
            va="bottom",
            fontsize=note_fontsize,
            color=note_color,
            fontweight="bold",
            linespacing=1.48 if note_linespacing is None else note_linespacing,
            bbox=dict(
                boxstyle=f"round,pad={PPT_BOX_PADDING if note_padding is None else note_padding}",
                facecolor="#FFFFFF",
                edgecolor=note_edge,
                linewidth=PPT_BOX_LINEWIDTH if note_linewidth is None else note_linewidth,
                alpha=0.98,
            ),
        )

        if use_tight_layout:
            plt.tight_layout(rect=[0, bottom_margin, 1, 1])
    else:
        if use_tight_layout:
            plt.tight_layout()

    if SAVE_FIGURES:
        GRAPH_DIR.mkdir(parents=True, exist_ok=True)
        out_path = GRAPH_DIR / filename
        plt.savefig(out_path, dpi=GRAPH_DPI, bbox_inches="tight")
        print(f"그래프 저장: {out_path}")

    plt.show()
    plt.close()


def clear_old_graph_files():
    if not SAVE_FIGURES:
        return

    if not GRAPH_DIR.exists():
        return

    removed_count = 0
    for path in GRAPH_DIR.glob("*.png"):
        path.unlink()
        removed_count += 1

    print(f"기존 그래프 삭제: {removed_count}개")


def load_base_result():
    global pb

    search_dir = setup_paths()
    set_korean_font()

    import project_base
    pb = project_base

    return pb.run_base_pipeline(search_dir=search_dir)


def display_table(title, df):
    print(f"\n[{title}]")
    display(df)


# ============================================================
# 시각화 보정
# - 교통량 값의 차이가 작아 막대/선이 일자로 보이는 그래프는 y축 또는 x축을 확대한다.
# - 하단이 생략된 그래프도 별도 안내 문구 없이 축 범위만 조정한다.
# ============================================================

def _numeric_values(values):
    arr = pd.Series(np.ravel(values)).dropna().astype(float)
    arr = arr[np.isfinite(arr)]
    return arr


def _format_number_axis(ax, axis="y"):
    try:
        from matplotlib.ticker import FuncFormatter
        formatter = FuncFormatter(lambda x, pos: f"{x:,.0f}")

        if axis == "y":
            ax.yaxis.set_major_formatter(formatter)
        else:
            ax.xaxis.set_major_formatter(formatter)
    except Exception:
        pass


def apply_zoom_y(ax, values, lower_margin=0.35, upper_margin=0.65, note=None):
    # note 인자는 기존 호출부 호환용으로만 남김.
    arr = _numeric_values(values)

    if len(arr) == 0:
        return

    vmin = float(arr.min())
    vmax = float(arr.max())
    spread = vmax - vmin

    if spread <= 0:
        spread = max(abs(vmax) * 0.03, 1.0)

    y_min = vmin - spread * lower_margin
    y_max = vmax + spread * upper_margin

    if vmin >= 0:
        y_min = max(0, y_min)

    if y_max <= y_min:
        y_max = y_min + spread

    ax.set_ylim(y_min, y_max)
    _format_number_axis(ax, "y")


def apply_zoom_x(ax, values, lower_margin=0.35, upper_margin=0.90, note=None):
    # note 인자는 기존 호출부 호환용으로만 남김.
    arr = _numeric_values(values)

    if len(arr) == 0:
        return

    vmin = float(arr.min())
    vmax = float(arr.max())
    spread = vmax - vmin

    if spread <= 0:
        spread = max(abs(vmax) * 0.03, 1.0)

    x_min = vmin - spread * lower_margin
    x_max = vmax + spread * upper_margin

    if vmin >= 0:
        x_min = max(0, x_min)

    if x_max <= x_min:
        x_max = x_min + spread

    ax.set_xlim(x_min, x_max)
    _format_number_axis(ax, "x")


# ============================================================
# 지성: 특정 날짜·시간대 예상 혼잡도
# 발표용 최종 출력 그래프: 4개
# 1) 2026~2030 어린이날 18시 예상 혼잡 지점 TOP5
# 2) 2026~2030 어린이날 가장 혼잡한 시간대 변화 예측
# 3) 2030년 5월 요일×시간대 예상 혼잡도 패턴
# 4) 2026~2030년 어린이날 예상 혼잡도 등급 구성 비교
# ============================================================

TARGET_MONTH_DAY = "05-05"
TARGET_MONTH = int(TARGET_MONTH_DAY.split("-")[0])
TARGET_DAY = int(TARGET_MONTH_DAY.split("-")[1])
TARGET_DAY_LABEL = "어린이날"
TARGET_MONTH_DAY_LABEL = f"{TARGET_MONTH}월 {TARGET_DAY}일"
TARGET_HOUR = 18
TARGET_YEAR_FOR_24H = 2030
PRED_YEARS = list(range(2026, 2031))
TIME_BINS = [0, 6, 9, 12, 15, 18, 21, 24]
TIME_LABELS = ["00~06", "06~09", "09~12", "12~15", "15~18", "18~21", "21~24"]
WEEKDAY_ORDER = ["월", "화", "수", "목", "금", "토", "일"]
LEVEL_ORDER = ["여유", "보통", "혼잡", "매우 혼잡"]


# ============================================================
# Alpha 스타일 최소 반영
# - 기존 Alpha ipynb의 발표용 그래프 톤을 참고함.
# - 계산 로직은 건드리지 않고, 제목/색상/요약 카드/격자만 정리함.
# ============================================================

ALPHA_TEXT = "#111827"
ALPHA_SUBTEXT = "#4B5563"
ALPHA_GRID = "#E5E7EB"

ALPHA_BLUE = "#2563EB"
ALPHA_RED = "#DC2626"
ALPHA_ORANGE = "#F59E0B"
ALPHA_TEAL = "#14B8A6"

LEVEL_COLOR_MAP = {
    "여유": "#14B8A6",
    "보통": "#F59E0B",
    "혼잡": "#EF4444",
    "매우 혼잡": "#DC2626",
}


def apply_alpha_axis_style(ax, grid_axis="y"):
    ax.set_facecolor("#FFFFFF")

    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)

    ax.spines["left"].set_color(ALPHA_GRID)
    ax.spines["bottom"].set_color(ALPHA_GRID)
    ax.tick_params(axis="both", colors=ALPHA_SUBTEXT)

    if grid_axis is not None:
        ax.grid(axis=grid_axis, alpha=0.25, color=ALPHA_GRID)


def set_alpha_title(ax, title, subtitle=None):
    # subtitle 인자는 기존 호출부 호환용으로만 남긴다.
    # 발표용 그래프에서는 제목만 출력한다.
    ax.set_title(
        title,
        fontsize=17,
        fontweight="bold",
        color=ALPHA_TEXT,
        pad=15,
    )


def add_alpha_summary_box(
    ax,
    text,
    x=0.98,
    y=0.96,
    ha="right",
    va="top",
    fontsize=PPT_SIDE_BOX_FONT_SIZE,
    fontweight="bold",
    linespacing=1.46,
    clip_on=False,
    box_padding=None,
    box_linewidth=None,
):
    ax.text(
        x,
        y,
        text,
        transform=ax.transAxes,
        ha=ha,
        va=va,
        fontsize=fontsize,
        fontweight=fontweight,
        color=ALPHA_TEXT,
        linespacing=linespacing,
        clip_on=clip_on,
        bbox=dict(
            boxstyle=f"round,pad={PPT_BOX_PADDING if box_padding is None else box_padding}",
            facecolor="#FFFFFF",
            edgecolor=ALPHA_TEXT,
            linewidth=PPT_BOX_LINEWIDTH if box_linewidth is None else box_linewidth,
            alpha=0.98,
        ),
    )


def make_prediction_note(target_text, result_text):
    # PPT에 넣으면 그래프가 축소되므로 하단 설명은 짧고 굵게 표시한다.
    return (
        "예측 기준: 2020~2025년 교통량 + 날짜·시간·도로 조건\n"
        f"계산 대상: {target_text}\n"
        "혼잡도 공식: 예상 교통량 ÷ 2025년 같은 지점 혼잡 기준 × 100\n"
        f"그래프 결과: {result_text}"
    )

def date_for_year(month_day, year):
    text = str(month_day).strip()

    if len(text) == 5 and text[2] == "-":
        return f"{year}-{text}"

    dt = pd.to_datetime(text)
    return f"{year}-{dt.month:02d}-{dt.day:02d}"


def observed_hours_for_date(base_result, target_date):
    dt = pd.to_datetime(target_date)
    day_type = pb.get_day_type(dt)

    available = (
        base_result["common_hour"]
        .loc[
            (base_result["common_hour"]["month"] == dt.month)
            & (base_result["common_hour"]["day_type"] == day_type),
            "hour_start",
        ]
        .dropna()
        .astype(int)
        .sort_values()
        .unique()
        .tolist()
    )

    return available


def build_hour_thresholds(common_hour, base_year=2025):
    # Alpha 흐름 반영: 혼잡 기준은 전체 연도 평균보다 2025년 기준선(q50/q75/q90)을 우선 사용함.
    data = common_hour.copy()

    if "year" in data.columns:
        year_num = pd.to_numeric(data["year"], errors="coerce")
        base_data = data[year_num == base_year].copy()

        if len(base_data) > 0:
            data = base_data

    thresholds = (
        data.groupby(["spot_num", "io_type"], observed=True)["vol_hour_avg"]
        .quantile([0.50, 0.75, 0.90])
        .unstack()
        .reset_index()
    )
    thresholds.columns = ["spot_num", "io_type", "q50", "q75", "q90"]

    return thresholds


# ============================================================
# Alpha 보정 로직 반영
# - 기존 project_base의 hour_model 예측값은 유지한다.
# - 예측 후 요일별 패턴 보정과 2023~2025 최근 증가율 보정을 약하게 적용한다.
# - 목적: 2026~2030 결과가 너무 평평하게 보이는 문제를 줄인다.
# ============================================================

WEEKDAY_CORRECTION_STRENGTH = 0.45
RECENT_GROWTH_CORRECTION_STRENGTH = 0.50

MIN_WEEKDAY_RATIO = 0.80
MAX_WEEKDAY_RATIO = 1.20
MIN_GROWTH_RATE_FOR_MODEL = -0.08
MAX_GROWTH_RATE_FOR_MODEL = 0.08
MIN_TOTAL_MULTIPLIER = 0.80
MAX_TOTAL_MULTIPLIER = 1.25

WEEKDAY_CODE_MAP = {
    0: "월",
    1: "화",
    2: "수",
    3: "목",
    4: "금",
    5: "토",
    6: "일",
}


def build_prediction_upgrade_context(base_result):
    common_weekday = base_result["common_weekday"].copy()
    common_hour = base_result["common_hour"].copy()

    # ------------------------------------------------------------
    # 1) 요일 보정 비율
    # ------------------------------------------------------------
    weekday_ratio_source = common_weekday.copy()
    weekday_ratio_source["month"] = pd.to_numeric(weekday_ratio_source["month"], errors="coerce")
    weekday_ratio_source["io_type"] = pd.to_numeric(weekday_ratio_source["io_type"], errors="coerce")
    weekday_ratio_source["vol_daily_avg"] = pd.to_numeric(weekday_ratio_source["vol_daily_avg"], errors="coerce")

    weekday_ratio_source = weekday_ratio_source.dropna(
        subset=["month", "io_type", "vol_daily_avg", "weekday_code"]
    ).copy()

    weekday_ratio_source["month"] = weekday_ratio_source["month"].astype(int)
    weekday_ratio_source["io_type"] = weekday_ratio_source["io_type"].astype(int)
    weekday_ratio_source["spot_num"] = weekday_ratio_source["spot_num"].astype(str)
    weekday_ratio_source["road_type"] = weekday_ratio_source["road_type"].astype(str)
    weekday_ratio_source["weekday_code"] = weekday_ratio_source["weekday_code"].astype(str)

    weekday_base_cols = ["month", "spot_num", "road_type", "io_type"]

    weekday_avg = (
        weekday_ratio_source
        .groupby(weekday_base_cols + ["weekday_code"], as_index=False, observed=True)["vol_daily_avg"]
        .mean()
        .rename(columns={"vol_daily_avg": "weekday_avg_vol"})
    )

    weekday_month_avg = (
        weekday_ratio_source
        .groupby(weekday_base_cols, as_index=False, observed=True)["vol_daily_avg"]
        .mean()
        .rename(columns={"vol_daily_avg": "weekday_base_avg_vol"})
    )

    weekday_ratio_table = weekday_avg.merge(weekday_month_avg, on=weekday_base_cols, how="left")
    weekday_ratio_table["weekday_ratio"] = np.where(
        weekday_ratio_table["weekday_base_avg_vol"] > 0,
        weekday_ratio_table["weekday_avg_vol"] / weekday_ratio_table["weekday_base_avg_vol"],
        1.0,
    )
    weekday_ratio_table["weekday_ratio"] = (
        weekday_ratio_table["weekday_ratio"]
        .replace([np.inf, -np.inf], np.nan)
        .fillna(1.0)
        .clip(MIN_WEEKDAY_RATIO, MAX_WEEKDAY_RATIO)
    )
    weekday_ratio_table = weekday_ratio_table[weekday_base_cols + ["weekday_code", "weekday_ratio"]].copy()

    # ------------------------------------------------------------
    # 2) 2023~2025 최근 증가율
    # ------------------------------------------------------------
    keys = ["spot_num", "month", "day_type", "hour_start", "io_type"]
    growth_source = common_hour.copy()
    growth_source["year"] = pd.to_numeric(growth_source["year"], errors="coerce")
    growth_source["month"] = pd.to_numeric(growth_source["month"], errors="coerce")
    growth_source["hour_start"] = pd.to_numeric(growth_source["hour_start"], errors="coerce")
    growth_source["io_type"] = pd.to_numeric(growth_source["io_type"], errors="coerce")
    growth_source["vol_hour_avg"] = pd.to_numeric(growth_source["vol_hour_avg"], errors="coerce")

    growth_source = growth_source.dropna(
        subset=["year", "month", "hour_start", "io_type", "vol_hour_avg"]
    ).copy()

    growth_source = growth_source[growth_source["year"].isin([2023, 2024, 2025])].copy()
    growth_source["year"] = growth_source["year"].astype(int)
    growth_source["month"] = growth_source["month"].astype(int)
    growth_source["hour_start"] = growth_source["hour_start"].astype(int)
    growth_source["io_type"] = growth_source["io_type"].astype(int)
    growth_source["spot_num"] = growth_source["spot_num"].astype(str)
    growth_source["day_type"] = growth_source["day_type"].astype(str)

    if len(growth_source) > 0:
        growth_base = growth_source.groupby(["year"] + keys, as_index=False, observed=True)["vol_hour_avg"].mean()
        pivot_growth = growth_base.pivot_table(index=keys, columns="year", values="vol_hour_avg").reset_index()

        def calc_growth_rate(row):
            if pd.notna(row.get(2023)) and pd.notna(row.get(2025)) and row.get(2023) > 0:
                return (row.get(2025) / row.get(2023)) ** (1 / 2) - 1

            if pd.notna(row.get(2024)) and pd.notna(row.get(2025)) and row.get(2024) > 0:
                return row.get(2025) / row.get(2024) - 1

            return np.nan

        pivot_growth["growth_rate"] = pivot_growth.apply(calc_growth_rate, axis=1)
        global_growth_rate = pivot_growth["growth_rate"].dropna().median()

        if pd.isna(global_growth_rate):
            global_growth_rate = 0.0

        pivot_growth["growth_rate"] = (
            pivot_growth["growth_rate"]
            .fillna(global_growth_rate)
            .clip(-0.20, 0.20)
        )
        pivot_growth = pivot_growth[keys + ["growth_rate"]].copy()
    else:
        global_growth_rate = 0.0
        pivot_growth = pd.DataFrame(columns=keys + ["growth_rate"])

    print("요일 보정 비율 테이블 크기:", weekday_ratio_table.shape)
    print("최근 증가율 기준값:", round(float(global_growth_rate), 4))
    print("최근 증가율 테이블 크기:", pivot_growth.shape)

    return {
        "weekday_ratio_table": weekday_ratio_table,
        "pivot_growth": pivot_growth,
        "global_growth_rate": float(global_growth_rate),
        "growth_keys": keys,
    }


def apply_prediction_upgrade(data, upgrade_context, target_date_value, year_col="year"):
    if upgrade_context is None:
        return data

    result = data.copy()

    remove_cols = [
        "weekday_code", "weekday_ratio", "weekday_multiplier",
        "growth_rate", "growth_rate_for_model", "future_gap",
        "recent_growth_multiplier", "total_prediction_multiplier",
        "predicted_vol_before_adjust",
    ]

    for col in remove_cols:
        if col in result.columns:
            result = result.drop(columns=[col])

    result["predicted_vol_before_adjust"] = pd.to_numeric(result["predicted_vol"], errors="coerce")

    target_series = pd.Series(
        pd.to_datetime([target_date_value] * len(result), errors="coerce"),
        index=result.index,
    )
    result["weekday_code"] = target_series.dt.weekday.map(WEEKDAY_CODE_MAP)

    weekday_ratio_table = upgrade_context["weekday_ratio_table"].copy()
    merge_cols = ["month", "spot_num", "road_type", "io_type", "weekday_code"]

    for df in [result, weekday_ratio_table]:
        df["month"] = pd.to_numeric(df["month"], errors="coerce").astype("Int64")
        df["io_type"] = pd.to_numeric(df["io_type"], errors="coerce").astype("Int64")
        df["spot_num"] = df["spot_num"].astype(str)
        df["road_type"] = df["road_type"].astype(str)
        df["weekday_code"] = df["weekday_code"].astype(str)

    result = result.merge(weekday_ratio_table, on=merge_cols, how="left")
    result["weekday_ratio"] = result["weekday_ratio"].fillna(1.0)
    result["weekday_multiplier"] = 1 + ((result["weekday_ratio"] - 1) * WEEKDAY_CORRECTION_STRENGTH)

    pivot_growth = upgrade_context["pivot_growth"].copy()
    growth_keys = upgrade_context["growth_keys"]
    global_growth_rate = upgrade_context["global_growth_rate"]

    if len(pivot_growth) > 0:
        for df in [result, pivot_growth]:
            df["spot_num"] = df["spot_num"].astype(str)
            df["day_type"] = df["day_type"].astype(str)
            df["month"] = pd.to_numeric(df["month"], errors="coerce").astype("Int64")
            df["hour_start"] = pd.to_numeric(df["hour_start"], errors="coerce").astype("Int64")
            df["io_type"] = pd.to_numeric(df["io_type"], errors="coerce").astype("Int64")

        result = result.merge(pivot_growth[growth_keys + ["growth_rate"]], on=growth_keys, how="left")
    else:
        result["growth_rate"] = global_growth_rate

    result["growth_rate_for_model"] = (
        pd.to_numeric(result["growth_rate"], errors="coerce")
        .fillna(global_growth_rate)
        .clip(MIN_GROWTH_RATE_FOR_MODEL, MAX_GROWTH_RATE_FOR_MODEL)
    )

    result["future_gap"] = pd.to_numeric(result[year_col], errors="coerce") - 2025
    result["future_gap"] = result["future_gap"].fillna(0).clip(0, 5)

    result["recent_growth_multiplier"] = (
        1 + result["growth_rate_for_model"] * RECENT_GROWTH_CORRECTION_STRENGTH
    ) ** result["future_gap"]

    result["total_prediction_multiplier"] = (
        result["weekday_multiplier"] * result["recent_growth_multiplier"]
    ).clip(MIN_TOTAL_MULTIPLIER, MAX_TOTAL_MULTIPLIER)

    result["predicted_vol"] = result["predicted_vol_before_adjust"] * result["total_prediction_multiplier"]
    result["predicted_vol"] = (
        result["predicted_vol"]
        .replace([np.inf, -np.inf], np.nan)
        .fillna(result["predicted_vol_before_adjust"])
    )
    result["predicted_vol"] = np.round(result["predicted_vol"], 0).astype(int)

    return result


def predict_hourly_for_date(target_date, base_result, hour_start=None, observed_only=True, upgrade_context=None):
    inp = pb.make_specific_day_hour_input(
        target_date=target_date,
        station_latest=base_result["station_latest"],
        hour_start=hour_start,
    )

    if observed_only and hour_start is None:
        valid_hours = observed_hours_for_date(base_result, target_date)
        inp = inp[inp["hour_start"].isin(valid_hours)].copy()

    inp["predicted_vol"] = pb.predict_regression(base_result["hour_model"], inp)

    if upgrade_context is not None:
        inp = apply_prediction_upgrade(inp, upgrade_context, target_date_value=target_date, year_col="year")

    return inp


def add_congestion_score(pred_df, thresholds, station_latest):
    result = pred_df.copy()
    result["spot_num"] = result["spot_num"].astype("string")

    thresholds = thresholds.copy()
    thresholds["spot_num"] = thresholds["spot_num"].astype("string")

    result = result.merge(thresholds, on=["spot_num", "io_type"], how="left")

    fallback = thresholds["q90"].dropna().median()
    result["base_capacity"] = result["q90"].fillna(fallback)
    result["congestion_score"] = np.where(
        result["base_capacity"] > 0,
        result["predicted_vol"] / result["base_capacity"] * 100,
        np.nan,
    )
    result["congestion_score"] = np.round(result["congestion_score"], 1)

    # Alpha 혼잡도 등급 기준을 가볍게 반영한다.
    result["congestion_level"] = pd.cut(
        result["congestion_score"],
        bins=[-np.inf, 60, 85, 100, np.inf],
        labels=LEVEL_ORDER,
    ).astype(str)

    station_cols = ["spot_num", "spot_name", "road_type", "spot_location"]
    station_info = station_latest[station_cols].drop_duplicates("spot_num").copy()
    station_info["spot_num"] = station_info["spot_num"].astype("string")

    return result.merge(station_info, on="spot_num", how="left")


def build_top_congestion_spots(base_result, target_date, target_hour, thresholds, upgrade_context=None):
    pred = predict_hourly_for_date(
        target_date,
        base_result,
        hour_start=target_hour,
        upgrade_context=upgrade_context,
    )
    pred = add_congestion_score(pred, thresholds, base_result["station_latest"])

    return (
        pred.groupby(["spot_num", "spot_name"], as_index=False, observed=True)
        .agg(
            predicted_vol=("predicted_vol", "sum"),
            congestion_score=("congestion_score", "mean"),
        )
        .sort_values("congestion_score", ascending=False)
        .head(5)
    )


def build_top_congestion_spots_all_years(base_result, thresholds, upgrade_context=None):
    rows = []

    for year in PRED_YEARS:
        target_date = date_for_year(TARGET_MONTH_DAY, year)
        temp = build_top_congestion_spots(
            base_result,
            target_date,
            TARGET_HOUR,
            thresholds,
            upgrade_context=upgrade_context,
        ).copy()
        temp.insert(0, "year", year)
        temp.insert(1, "target_date", target_date)
        temp["rank"] = np.arange(1, len(temp) + 1)
        rows.append(temp)

    if len(rows) == 0:
        return pd.DataFrame(
            columns=["year", "target_date", "rank", "spot_num", "spot_name", "predicted_vol", "congestion_score"]
        )

    return pd.concat(rows, ignore_index=True)


def build_24h_flow(base_result, target_date, thresholds, upgrade_context=None):
    pred = predict_hourly_for_date(
        target_date,
        base_result,
        hour_start=None,
        upgrade_context=upgrade_context,
    )
    pred = add_congestion_score(pred, thresholds, base_result["station_latest"])

    hourly = (
        pred.groupby("hour_start", as_index=False)
        .agg(
            predicted_vol=("predicted_vol", "sum"),
            congestion_score=("congestion_score", "mean"),
        )
        .sort_values("hour_start")
    )

    return hourly, pred


def build_weekday_time_heatmap(base_result, thresholds, upgrade_context=None):
    rows = []
    month = pd.to_datetime(date_for_year(TARGET_MONTH_DAY, TARGET_YEAR_FOR_24H)).month
    start = pd.Timestamp(year=TARGET_YEAR_FOR_24H, month=month, day=1)

    for weekday_idx in range(7):
        dt = start

        while dt.weekday() != weekday_idx:
            dt += pd.Timedelta(days=1)

        pred = predict_hourly_for_date(
            str(dt.date()),
            base_result,
            hour_start=None,
            upgrade_context=upgrade_context,
        )
        pred = add_congestion_score(pred, thresholds, base_result["station_latest"])
        pred["weekday_code"] = WEEKDAY_ORDER[dt.weekday()]
        rows.append(pred[["weekday_code", "hour_start", "congestion_score"]])

    all_pred = pd.concat(rows, ignore_index=True)
    all_pred["time_bin"] = pd.cut(
        all_pred["hour_start"],
        bins=TIME_BINS,
        labels=TIME_LABELS,
        right=False,
        include_lowest=True,
    )

    heat = (
        all_pred.groupby(["weekday_code", "time_bin"], observed=True)["congestion_score"]
        .mean()
        .unstack("time_bin")
    )

    return heat.reindex(index=WEEKDAY_ORDER, columns=TIME_LABELS)


def build_peak_by_year(base_result, thresholds, upgrade_context=None):
    rows = []

    for year in PRED_YEARS:
        target_date = date_for_year(TARGET_MONTH_DAY, year)
        hourly, _ = build_24h_flow(base_result, target_date, thresholds, upgrade_context=upgrade_context)
        peak = hourly.loc[hourly["congestion_score"].idxmax()]

        rows.append({
            "year": year,
            "target_date": target_date,
            "peak_hour": int(peak["hour_start"]),
            "peak_score": float(peak["congestion_score"]),
            "peak_vol": float(peak["predicted_vol"]),
        })

    return pd.DataFrame(rows)


def build_level_distribution_all_years(base_result, thresholds, upgrade_context=None):
    rows = []

    for year in PRED_YEARS:
        target_date = date_for_year(TARGET_MONTH_DAY, year)
        _, pred_detail = build_24h_flow(
            base_result,
            target_date,
            thresholds,
            upgrade_context=upgrade_context,
        )

        counts = pred_detail["congestion_level"].value_counts().reindex(LEVEL_ORDER).fillna(0)
        total_count = counts.sum()

        if total_count == 0:
            pct = counts.copy()
        else:
            pct = counts / total_count * 100

        row = {
            "year": year,
            "target_date": target_date,
            "total_count": int(total_count),
        }

        for level in LEVEL_ORDER:
            row[level] = float(pct.get(level, 0))

        row["혼잡 구간"] = float(
            pct.reindex(["혼잡", "매우 혼잡"]).fillna(0).sum()
        )
        row["가장 많은 등급"] = pct.idxmax()
        row["가장 많은 등급 비중"] = float(pct.max())

        rows.append(row)

    return pd.DataFrame(rows)


# ============================================================
# 발표용 그래프 4개
# ============================================================

def plot_top_congestion_spots_all_years(top_all, target_hour):
    if top_all is None or len(top_all) == 0:
        print("혼잡 지점 TOP5를 만들 데이터가 없습니다.")
        return

    plot_df = top_all.sort_values(["year", "rank"], ascending=[True, True]).copy()
    plot_df["spot_label"] = plot_df["spot_name"].fillna(plot_df["spot_num"]).astype(str)

    def shorten_label(text, max_len=18):
        text = str(text)
        if len(text) <= max_len:
            return text
        return text[:max_len - 1] + "…"

    plot_df["short_spot_label"] = plot_df["spot_label"].apply(shorten_label)

    y_positions = []
    y_labels = []
    group_ranges = {}

    y = 0
    group_gap = 0.65

    for year, group in plot_df.groupby("year", sort=True):
        start_y = y

        for _, row in group.iterrows():
            y_positions.append(y)
            y_labels.append(f"{int(row['rank'])}위  {row['short_spot_label']}")
            y += 1

        end_y = y - 1
        group_ranges[int(year)] = (start_y, end_y)
        y += group_gap

    plot_df["y_pos"] = y_positions

    max_idx = plot_df["congestion_score"].idxmax()

    colors = []
    for idx, row in plot_df.iterrows():
        if idx == max_idx:
            colors.append(ALPHA_RED)
        elif int(row["rank"]) == 1:
            colors.append(ALPHA_BLUE)
        else:
            colors.append("#D1D5DB")

    # 2026~2030년 × TOP5 = 25행이 한 장에 들어가므로,
    # 1번 그래프는 다른 그래프보다 넓은 전용 캔버스를 사용한다.
    # PPT의 16:9 화면에 넣었을 때 세로로 긴 이미지가 지나치게 축소되지 않도록
    # 높이를 제한하고 그래프가 가로 폭을 더 많이 사용하게 한다.
    calculated_height = len(plot_df) * 0.38 + len(group_ranges) * 0.45
    fig_height = max(10.8, min(12.0, calculated_height))
    fig, ax = plt.subplots(figsize=(21.2, fig_height))

    bars = ax.barh(
        plot_df["y_pos"],
        plot_df["congestion_score"],
        color=colors,
        height=0.68,
    )

    set_alpha_title(
        ax,
        f"2026~2030년 {TARGET_DAY_LABEL} {target_hour:02d}시 혼잡 지점 TOP5 예측",
    )

    ax.set_xlabel("혼잡도 점수(%)", color=ALPHA_TEXT)
    ax.set_ylabel("")
    ax.set_yticks(plot_df["y_pos"])
    ax.set_yticklabels(y_labels, fontsize=10.0, fontweight="bold", color=ALPHA_TEXT)
    ax.tick_params(axis="y", pad=8)
    ax.invert_yaxis()

    apply_alpha_axis_style(ax, grid_axis="x")
    apply_zoom_x(ax, plot_df["congestion_score"], upper_margin=1.25)

    # 왼쪽은 연도 라벨 + 순위 + 지점명 공간,
    # 오른쪽은 설명 박스 공간, 아래쪽은 예측 기준 설명문 공간으로 분리한다.
    fig.subplots_adjust(left=0.28, right=0.75, top=0.90, bottom=0.17)

    x_min, x_max = ax.get_xlim()
    x_range = x_max - x_min

    for group_idx, (year, (start_y, end_y)) in enumerate(group_ranges.items()):
        if group_idx % 2 == 0:
            ax.axhspan(
                start_y - 0.46,
                end_y + 0.46,
                color="#F9FAFB",
                alpha=0.95,
                zorder=0,
            )

        center_y = (start_y + end_y) / 2

        ax.text(
            x_min - x_range * 0.28,
            center_y,
            f"{year}년",
            ha="right",
            va="center",
            fontsize=12.8,
            fontweight="bold",
            color=ALPHA_TEXT,
            clip_on=False,
        )

        ax.axhline(
            end_y + 0.5,
            color=ALPHA_GRID,
            linewidth=1.2,
            zorder=0,
        )

    for bar, value in zip(bars, plot_df["congestion_score"]):
        ax.text(
            value + x_range * 0.012,
            bar.get_y() + bar.get_height() / 2,
            f"{value:.1f}%",
            va="center",
            fontsize=10.2,
            fontweight="bold",
            color=ALPHA_TEXT,
        )

    top_row = plot_df.loc[max_idx]
    ax.scatter(
        [top_row["congestion_score"]],
        [top_row["y_pos"]],
        s=58,
        color=ALPHA_RED,
        zorder=5,
    )

    summary_text = (
        "가장 높은 혼잡 예측\n"
        f"{int(top_row['year'])}년 {TARGET_DAY_LABEL}\n"
        f"{top_row['spot_label']}\n"
        f"혼잡도 {top_row['congestion_score']:.1f}%"
    )
    add_alpha_summary_box(ax, summary_text, x=1.03, y=0.98, ha="left")

    guide_text = (
        "읽는 법\n"
        "왼쪽: 예측 연도\n"
        "행: 순위 + 지점\n"
        "오른쪽: 혼잡도 점수"
    )
    add_alpha_summary_box(ax, guide_text, x=1.03, y=0.72, ha="left")

    score_guide_text = (
        "혼잡도 점수 기준\n"
        "예상 교통량을 최근 기준 혼잡선과 비교\n"
        "100% = 최근 높은 혼잡 기준선 수준\n"
        "100% 초과 = 기준보다 더 혼잡 예상"
    )
    add_alpha_summary_box(ax, score_guide_text, x=1.03, y=0.44, ha="left")

    add_alpha_summary_box(
        ax,
        "색상 의미\n회색: 일반 순위\n파랑: 연도별 1위\n빨강: 전체 최고 예측",
        x=1.03,
        y=0.20,
        ha="left",
        fontsize=12.0,
    )

    bottom_note = make_prediction_note(
        target_text="연도별 어린이날 18시 예상 교통량",
        result_text="혼잡도 TOP5 지점을 연도별 비교",
    )

    save_and_show(
        "지성_01_2026_2030_혼잡지점_TOP5.png",
        bottom_note=bottom_note,
        bottom_margin=0.17,
        note_y=0.012,
        note_fontsize=PPT_BOTTOM_NOTE_FONT_SIZE,
        use_tight_layout=False,
    )


def plot_peak_by_year(peak_df):
    # 사용자가 지정한 이전 발표 이미지 구성:
    # 선그래프를 전체 폭으로 사용하고 설명 탭은 그래프 내부에 배치한다.
    fig, ax = plt.subplots(figsize=(11.5, 6.2))

    ax.axvspan(
        PRED_YEARS[0] - 0.35,
        PRED_YEARS[-1] + 0.35,
        color="#EEF2FF",
        alpha=0.75,
    )

    ax.plot(
        peak_df["year"],
        peak_df["peak_score"],
        marker="o",
        linewidth=2.8,
        markersize=7,
        color=ALPHA_RED,
        markerfacecolor="#FFFFFF",
        markeredgewidth=2,
        markeredgecolor=ALPHA_RED,
    )

    set_alpha_title(
        ax,
        f"2026~2030년 {TARGET_DAY_LABEL} 가장 혼잡한 시간대 변화 예측 (최고 혼잡 시간대)",
    )

    ax.set_xlabel("연도", color=ALPHA_TEXT)
    ax.set_ylabel("최고 혼잡도 점수", color=ALPHA_TEXT)
    ax.set_xticks(peak_df["year"])

    apply_alpha_axis_style(ax, grid_axis="y")
    apply_zoom_y(ax, peak_df["peak_score"])

    try:
        from matplotlib.ticker import FuncFormatter
        ax.yaxis.set_major_formatter(FuncFormatter(lambda x, pos: f"{x:.0f}%"))
    except Exception:
        pass

    y_min, y_max = ax.get_ylim()
    y_gap = (y_max - y_min) * 0.045

    for _, row in peak_df.iterrows():
        dt = pd.to_datetime(row["target_date"])
        label = (
            f"{dt.year}년 {dt.month}월 {dt.day}일\n"
            f"{int(row['peak_hour'])}시\n"
            f"{row['peak_score']:.1f}%"
        )

        ax.text(
            row["year"],
            row["peak_score"] + y_gap,
            label,
            ha="center",
            va="bottom",
            fontsize=9.8,
            fontweight="bold",
            color=ALPHA_TEXT,
        )

    max_row = peak_df.loc[peak_df["peak_score"].idxmax()]
    min_row = peak_df.loc[peak_df["peak_score"].idxmin()]

    max_dt = pd.to_datetime(max_row["target_date"])
    min_dt = pd.to_datetime(min_row["target_date"])

    summary_text = (
        "핵심 요약\n"
        f"최고: {max_dt.year}년 {max_dt.month}월 {max_dt.day}일 "
        f"{int(max_row['peak_hour'])}시 / {max_row['peak_score']:.1f}%\n"
        f"최저: {min_dt.year}년 {min_dt.month}월 {min_dt.day}일 "
        f"{int(min_row['peak_hour'])}시 / {min_row['peak_score']:.1f}%"
    )
    add_alpha_summary_box(
        ax,
        summary_text,
        x=0.98,
        y=0.95,
        ha="right",
        fontsize=11.2,
        linespacing=1.40,
        box_padding=0.55,
        box_linewidth=1.1,
    )

    explain_text = (
        "혼잡도 점수 해석\n"
        "100% = 최근 기준 혼잡선 수준\n"
        "100% 초과 = 기준보다 더 혼잡할 가능성"
    )
    add_alpha_summary_box(
        ax,
        explain_text,
        x=0.02,
        y=0.18,
        ha="left",
        va="bottom",
        fontsize=11.2,
        linespacing=1.40,
        box_padding=0.55,
        box_linewidth=1.1,
    )

    bottom_note = make_prediction_note(
        target_text="연도별 어린이날 0~23시 예상 교통량",
        result_text="가장 높은 혼잡 시간대를 연도별 표시",
    )

    save_and_show(
        "지성_02_2026_2030_최고혼잡시간대변화.png",
        bottom_note=bottom_note,
        bottom_margin=0.23,
        note_y=0.020,
        note_fontsize=9.6,
        note_linespacing=1.38,
        note_padding=0.50,
        note_linewidth=1.15,
    )


def plot_weekday_time_heatmap(heat):
    if heat is None or len(heat) == 0:
        print("요일×시간대 히트맵을 만들 데이터가 없습니다.")
        return

    import matplotlib.colors as mcolors

    data = heat.astype(float).copy()
    values = data.values
    valid_values = values[np.isfinite(values)]

    if len(valid_values) == 0:
        print("요일×시간대 히트맵에 표시할 값이 없습니다.")
        return

    min_value = float(np.nanmin(valid_values))
    max_value = float(np.nanmax(valid_values))

    def make_heat_color(value):
        if pd.isna(value):
            return "#F3F4F6"

        if max_value == min_value:
            ratio = 0.5
        else:
            ratio = (float(value) - min_value) / (max_value - min_value)

        ratio = max(0, min(1, ratio))
        return mcolors.to_hex(plt.cm.YlGnBu(0.18 + ratio * 0.72))

    fig, ax = plt.subplots(figsize=(16.8, 9.4))
    ax.set_xlim(0, len(data.columns))
    ax.set_ylim(-0.68, len(data.index) + 1.05)
    ax.invert_yaxis()
    ax.axis("off")

    ax.text(
        0,
        -0.45,
        f"{TARGET_YEAR_FOR_24H}년 {TARGET_MONTH}월 요일·시간대별 예상 혼잡도 패턴",
        ha="left",
        va="center",
        fontsize=18,
        fontweight="bold",
        color=ALPHA_TEXT,
    )

    for col_idx, col_name in enumerate(data.columns):
        ax.text(
            col_idx + 0.5,
            0.05,
            str(col_name),
            ha="center",
            va="center",
            fontsize=11.2,
            fontweight="bold",
            color=ALPHA_TEXT,
        )

    for row_idx, row_name in enumerate(data.index):
        y_base = row_idx + 0.35

        ax.text(
            -0.25,
            y_base + 0.5,
            str(row_name),
            ha="right",
            va="center",
            fontsize=11.7,
            fontweight="bold",
            color=ALPHA_TEXT,
        )

        for col_idx, col_name in enumerate(data.columns):
            value = data.loc[row_name, col_name]
            cell_color = make_heat_color(value)

            edge_color = "#FFFFFF"
            line_width = 1.4

            if pd.notna(value) and float(value) == max_value:
                edge_color = ALPHA_RED
                line_width = 2.2
            elif pd.notna(value) and float(value) == min_value:
                edge_color = ALPHA_TEAL
                line_width = 2.2

            rect = plt.Rectangle(
                (col_idx + 0.04, y_base + 0.04),
                0.92,
                0.92,
                linewidth=line_width,
                edgecolor=edge_color,
                facecolor=cell_color,
            )
            ax.add_patch(rect)

            if pd.isna(value):
                text = ""
                text_color = ALPHA_SUBTEXT
            else:
                text = f"{value:.0f}"
                color_ratio = 0.5 if max_value == min_value else (float(value) - min_value) / (max_value - min_value)
                text_color = "#FFFFFF" if color_ratio >= 0.62 else ALPHA_TEXT

            ax.text(
                col_idx + 0.5,
                y_base + 0.5,
                text,
                ha="center",
                va="center",
                fontsize=11.3,
                fontweight="bold",
                color=text_color,
            )

    max_pos = np.where(values == max_value)
    min_pos = np.where(values == min_value)

    max_day = data.index[max_pos[0][0]]
    max_time = data.columns[max_pos[1][0]]
    min_day = data.index[min_pos[0][0]]
    min_time = data.columns[min_pos[1][0]]

    summary_text = (
        "핵심 요약\n"
        f"최고: {max_day} {max_time} / {max_value:.1f}%\n"
        f"최저: {min_day} {min_time} / {min_value:.1f}%"
    )

    ax.text(
        len(data.columns) - 0.05,
        len(data.index) + 0.92,
        summary_text,
        ha="right",
        va="top",
        fontsize=12.0,
        fontweight="bold",
        color=ALPHA_TEXT,
        bbox=dict(
            boxstyle=f"round,pad={PPT_BOX_PADDING}",
            facecolor="#FFFFFF",
            edgecolor=ALPHA_TEXT,
            linewidth=PPT_BOX_LINEWIDTH,
            alpha=0.98,
        ),
    )

    legend_y = len(data.index) + 0.62
    ax.text(
        0,
        legend_y,
        "낮음",
        ha="left",
        va="center",
        fontsize=10.2,
        fontweight="bold",
        color=ALPHA_TEXT,
    )

    for i in range(8):
        ratio = i / 7
        color = mcolors.to_hex(plt.cm.YlGnBu(0.18 + ratio * 0.72))
        rect = plt.Rectangle(
            (0.55 + i * 0.22, legend_y - 0.11),
            0.2,
            0.22,
            linewidth=0,
            facecolor=color,
        )
        ax.add_patch(rect)

    ax.text(
        2.55,
        legend_y,
        "높음",
        ha="left",
        va="center",
        fontsize=10.2,
        fontweight="bold",
        color=ALPHA_TEXT,
    )

    bottom_note = make_prediction_note(
        target_text="2030년 5월 대표 요일·시간대 예상 교통량",
        result_text="요일·시간대 평균 혼잡도를 색상으로 비교",
    )

    save_and_show(
        "지성_03_요일_시간대_혼잡도_히트맵.png",
        bottom_note=bottom_note,
        bottom_margin=0.18,
        note_y=0.012,
        note_fontsize=PPT_BOTTOM_NOTE_FONT_SIZE,
    )


def plot_level_distribution_all_years(level_all, seq=4):
    if level_all is None or len(level_all) == 0:
        print("연도별 혼잡도 등급 구성을 만들 데이터가 없습니다.")
        return

    data = level_all.sort_values("year").copy()

    # 사용자가 지정한 이전 발표 이미지 구성으로 복원한다.
    fig = plt.figure(figsize=(21.8, 11.6))
    gs = fig.add_gridspec(
        1,
        2,
        width_ratios=[4.85, 3.15],
        wspace=0.42,
    )

    ax = fig.add_subplot(gs[0, 0])
    panel_ax = fig.add_subplot(gs[0, 1])
    panel_ax.axis("off")
    panel_ax.set_xlim(0, 1)
    panel_ax.set_ylim(0, 1)

    y_pos = np.arange(len(data))
    left = np.zeros(len(data))

    for level in LEVEL_ORDER:
        values = data[level].astype(float).values

        bars = ax.barh(
            y_pos,
            values,
            left=left,
            color=LEVEL_COLOR_MAP.get(level, "#9CA3AF"),
            height=0.62,
            label=level,
        )

        for idx, (bar, value) in enumerate(zip(bars, values)):
            if value >= 7:
                text_color = "#FFFFFF" if level in ["혼잡", "매우 혼잡"] else ALPHA_TEXT

                ax.text(
                    left[idx] + value / 2,
                    bar.get_y() + bar.get_height() / 2,
                    f"{value:.0f}%",
                    ha="center",
                    va="center",
                    fontsize=10.3,
                    fontweight="bold",
                    color=text_color,
                )

        left += values

    set_alpha_title(
        ax,
        f"2026~2030년 {TARGET_DAY_LABEL} 예상 혼잡도 등급 구성 비교",
    )

    ax.set_yticks(y_pos)
    ax.set_yticklabels(
        data["year"].astype(int).astype(str) + "년",
        fontsize=12.0,
        fontweight="bold",
        color=ALPHA_TEXT,
    )

    ax.set_xlim(0, 112)
    ax.set_xticks([0, 20, 40, 60, 80, 100])
    ax.set_xlabel("등급별 비중(%)", color=ALPHA_TEXT)
    ax.invert_yaxis()

    apply_alpha_axis_style(ax, grid_axis="x")

    try:
        from matplotlib.ticker import FuncFormatter
        ax.xaxis.set_major_formatter(FuncFormatter(lambda x, pos: f"{x:.0f}%"))
    except Exception:
        pass

    max_risk_value = float(data["혼잡 구간"].max())

    for pos, (_, row) in enumerate(data.iterrows()):
        risk = float(row["혼잡 구간"])
        is_max = np.isclose(risk, max_risk_value)

        ax.text(
            103.0,
            pos,
            f"혼잡 구간 {risk:.1f}%",
            ha="left",
            va="center",
            fontsize=10.2,
            fontweight="bold",
            color=ALPHA_RED if is_max else ALPHA_SUBTEXT,
            clip_on=False,
        )

    max_idx = data["혼잡 구간"].idxmax()
    max_row = data.loc[max_idx]
    max_y = list(data.index).index(max_idx)

    ax.axhspan(
        max_y - 0.43,
        max_y + 0.43,
        color="#FEF2F2",
        alpha=0.65,
        zorder=0,
    )

    ax.text(
        0,
        max_y - 0.56,
        "혼잡 구간 비중 최고",
        ha="left",
        va="bottom",
        fontsize=10.2,
        fontweight="bold",
        color=ALPHA_RED,
    )

    ax.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.08),
        ncol=4,
        frameon=False,
        fontsize=10.5,
    )

    min_idx = data["혼잡 구간"].idxmin()
    min_row = data.loc[min_idx]
    latest_row = data.sort_values("year").iloc[-1]

    basis_text = (
        "기준 데이터\n"
        "2020~2025년 서울시 교통량 자료를 바탕으로\n"
        "2026~2030년 어린이날 교통량을 예측했습니다.\n\n"
        "예측에는 도로 지점, 도로 유형,\n"
        "유입·유출 방향, 요일 유형,\n"
        "시간대 조건이 함께 사용되었습니다."
    )
    add_alpha_summary_box(
        panel_ax,
        basis_text,
        x=0.02,
        y=0.98,
        ha="left",
        fontsize=9.4,
        fontweight="bold",
        linespacing=1.34,
        box_padding=0.55,
        box_linewidth=1.1,
    )

    read_text = (
        "그래프 읽는 법\n"
        "각 막대는 해당 연도의 예측 결과를\n"
        "100%로 본 구성비입니다.\n\n"
        "색이 넓을수록 그 등급으로 분류된\n"
        "구간이 많다는 뜻입니다."
    )
    add_alpha_summary_box(
        panel_ax,
        read_text,
        x=0.02,
        y=0.77,
        ha="left",
        fontsize=9.4,
        fontweight="bold",
        linespacing=1.34,
        box_padding=0.55,
        box_linewidth=1.1,
    )

    score_text = (
        "혼잡 정도 계산\n"
        "예상 교통량을 과거에 많이 막혔던\n"
        "교통량과 비교했습니다.\n\n"
        "혼잡 정도(%)\n"
        "= 예상 교통량 ÷ 2025년 같은 지점·방향의 과거 혼잡 기준 × 100\n\n"
        "기준 1,000대, 예상 900대 → 90%\n"
        "기준 1,000대, 예상 1,100대 → 110%\n\n"
        "100%를 넘으면 과거보다 더 혼잡할 가능성이 큽니다."
    )
    add_alpha_summary_box(
        panel_ax,
        score_text,
        x=0.02,
        y=0.58,
        ha="left",
        fontsize=8.5,
        fontweight="bold",
        linespacing=1.26,
        box_padding=0.55,
        box_linewidth=1.1,
    )

    level_text = (
        "등급 기준\n"
        "여유: 60% 미만\n"
        "보통: 60~85%\n"
        "혼잡: 85~100%\n"
        "매우 혼잡: 100% 이상\n\n"
        "혼잡 구간은 혼잡과 매우 혼잡을 합친 값입니다."
    )
    add_alpha_summary_box(
        panel_ax,
        level_text,
        x=0.02,
        y=0.30,
        ha="left",
        fontsize=9.1,
        fontweight="bold",
        linespacing=1.30,
        box_padding=0.55,
        box_linewidth=1.1,
    )

    summary_text = (
        "핵심 요약\n"
        f"혼잡 구간 최고: {int(max_row['year'])}년 {max_row['혼잡 구간']:.1f}%\n"
        f"혼잡 구간 최저: {int(min_row['year'])}년 {min_row['혼잡 구간']:.1f}%\n"
        f"2030년 최다 등급: {latest_row['가장 많은 등급']}"
    )
    # 이전 구성에서는 핵심 요약을 등급 기준 아래에 배치한다.
    add_alpha_summary_box(
        panel_ax,
        summary_text,
        x=0.02,
        y=0.135,
        ha="left",
        fontsize=9.6,
        fontweight="bold",
        linespacing=1.32,
        box_padding=0.55,
        box_linewidth=1.1,
    )

    # 이전 구성처럼 예측 기준 설명문을 오른쪽 패널 아래쪽에 배치한다.
    prediction_basis_text = (
        "예측 기준: 2020~2025년 교통량 + 날짜·시간·도로 조건\n"
        "계산 대상: 연도별 어린이날 전체 지점·시간대 예상 교통량\n"
        "혼잡도 공식: 예상 교통량 ÷ 2025년 동일 지점 혼잡 기준 × 100\n"
        "그래프 결과: 등급별 비중 비교"
    )
    add_alpha_summary_box(
        panel_ax,
        prediction_basis_text,
        x=0.02,
        y=-0.105,
        ha="left",
        va="bottom",
        fontsize=7.8,
        fontweight="bold",
        linespacing=1.16,
        clip_on=False,
        box_padding=0.55,
        box_linewidth=1.1,
    )

    fig.subplots_adjust(left=0.055, right=0.985, top=0.90, bottom=0.14)

    save_and_show(
        f"지성_{seq:02d}_2026_2030_혼잡도등급구성비교.png",
        use_tight_layout=False,
    )


def plot_level_distribution_year(pred_detail, target_date, seq):
    counts = pred_detail["congestion_level"].value_counts().reindex(LEVEL_ORDER).fillna(0)
    total_count = counts.sum()

    if total_count == 0:
        pct = counts.copy()
    else:
        pct = counts / total_count * 100

    colors = [LEVEL_COLOR_MAP.get(level, "#9CA3AF") for level in pct.index]

    fig, ax = plt.subplots(figsize=(10, 5.6))
    bars = ax.bar(
        pct.index,
        pct.values,
        color=colors,
        width=0.62,
    )

    set_alpha_title(
        ax,
        f"{pd.to_datetime(target_date).year}년 {TARGET_DAY_LABEL} 혼잡도 등급 구성",
    )

    ax.set_xlabel("혼잡도 등급", color=ALPHA_TEXT)
    ax.set_ylabel("비중(%)", color=ALPHA_TEXT)
    ax.set_ylim(0, 100)
    apply_alpha_axis_style(ax, grid_axis="y")

    for bar, value in zip(bars, pct.values):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            min(float(value) + 1.5, 98),
            f"{value:.1f}%",
            ha="center",
            va="bottom",
            fontsize=9,
            fontweight="bold",
            color=ALPHA_TEXT,
        )

    risk = float(pct.reindex(["혼잡", "매우 혼잡"]).fillna(0).sum())
    max_level = pct.idxmax()
    max_value = pct.max()

    summary_text = (
        "핵심 요약\n"
        f"혼잡 구간: {risk:.1f}%\n"
        f"가장 많은 등급: {max_level} {max_value:.1f}%\n"
        f"전체 기준 수: {int(total_count):,}건"
    )
    add_alpha_summary_box(ax, summary_text, x=0.98, y=0.95, ha="right")

    save_and_show(f"지성_{seq:02d}_{pd.to_datetime(target_date).year}년_혼잡등급_분포.png")


def main():
    base_result = load_base_result()

    # 이전 실행에서 저장된 불필요한 그래프가 섞이지 않도록 먼저 삭제
    clear_old_graph_files()

    thresholds = build_hour_thresholds(base_result["common_hour"])

    # Alpha ipynb 참고: 기존 hour_model 예측값은 유지하되,
    # 요일 패턴 + 2023~2025 최근 증가율을 약하게 반영해 결과가 너무 평평하게 보이는 문제를 줄인다.
    upgrade_context = build_prediction_upgrade_context(base_result)

    # ------------------------------------------------------------
    # 01. 2026~2030 어린이날 18시 예상 혼잡 지점 TOP5
    # ------------------------------------------------------------
    top_all = build_top_congestion_spots_all_years(
        base_result,
        thresholds,
        upgrade_context=upgrade_context,
    )
    display_table("2026~2030 어린이날 18시 예상 혼잡 지점 TOP5", top_all.round(2))
    plot_top_congestion_spots_all_years(top_all, TARGET_HOUR)

    # ------------------------------------------------------------
    # 02. 2026~2030 어린이날 가장 혼잡한 시간대 변화 예측
    # ------------------------------------------------------------
    peak_df = build_peak_by_year(
        base_result,
        thresholds,
        upgrade_context=upgrade_context,
    )
    display_table("2026~2030 어린이날 가장 혼잡한 시간대 변화 예측", peak_df.round(2))
    plot_peak_by_year(peak_df)

    # ------------------------------------------------------------
    # 03. 2030년 5월 요일×시간대 예상 혼잡도 패턴
    # ------------------------------------------------------------
    heat = build_weekday_time_heatmap(
        base_result,
        thresholds,
        upgrade_context=upgrade_context,
    )
    display_table("2030년 5월 요일×시간대 예상 혼잡도 패턴", heat.round(2))
    plot_weekday_time_heatmap(heat)

    # ------------------------------------------------------------
    # 04. 2026~2030년 어린이날 예상 혼잡도 등급 구성 비교
    # ------------------------------------------------------------
    level_all = build_level_distribution_all_years(
        base_result,
        thresholds,
        upgrade_context=upgrade_context,
    )

    display_cols = ["year", "target_date"] + LEVEL_ORDER + ["혼잡 구간", "가장 많은 등급"]
    display_table(
        "2026~2030년 어린이날 예상 혼잡도 등급 구성 비교",
        level_all[display_cols].round(2),
    )

    plot_level_distribution_all_years(level_all, 4)


if __name__ == "__main__":
    main()

