# -*- coding: utf-8 -*-
"""project수정본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihffuByWHIizbyAQI7YLbtBPREyJuLqz
"""

# -*- coding: utf-8 -*-
import os
import glob
import sys
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

try:
    from IPython.display import display
except Exception:
    display = print

SAVE_FIGURES = True
GRAPH_DIR = Path("traffic_final_graphs_v5")
GRAPH_DPI = 150


def _is_colab():
    try:
        import google.colab  # noqa: F401
        return True
    except Exception:
        return False


def maybe_upload_required_files():
    if not _is_colab():
        return
    search_dirs = [Path("/content"), Path.cwd()]
    has_zip = any(glob.glob(str(d / "*2020~2025 서울특별시 교통량 정제 데이터*.zip")) for d in search_dirs)
    has_base = any((d / "project_base.py").exists() for d in search_dirs)
    if not (has_zip and has_base):
        from google.colab import files
        print("필수 파일을 업로드하세요.")
        print(" - 2020~2025 서울특별시 교통량 정제 데이터.zip")
        print(" - project_base.py")
        files.upload()


def setup_paths():
    maybe_upload_required_files()
    for p in ["/content", os.getcwd()]:
        if p not in sys.path:
            sys.path.append(p)
    if Path("/content").exists():
        return "/content"
    return os.getcwd()


def set_korean_font():
    candidates = [
        "/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf",
        "/usr/share/fonts/truetype/nanum/NanumGothic.ttf",
    ]
    font_path = next((p for p in candidates if os.path.exists(p)), None)
    if font_path is None and _is_colab():
        subprocess.run(["apt-get", "-qq", "update"], check=False)
        subprocess.run(["apt-get", "-qq", "install", "-y", "fonts-nanum"], check=False)
        font_path = next((p for p in candidates if os.path.exists(p)), None)
    if font_path:
        fm.fontManager.addfont(font_path)
        font_name = fm.FontProperties(fname=font_path).get_name()
        plt.rc("font", family=font_name)
    else:
        plt.rc("font", family="DejaVu Sans")
    plt.rcParams["axes.unicode_minus"] = False
    plt.rcParams["figure.dpi"] = 120


def save_and_show(filename):
    plt.tight_layout()
    if SAVE_FIGURES:
        GRAPH_DIR.mkdir(parents=True, exist_ok=True)
        out_path = GRAPH_DIR / filename
        plt.savefig(out_path, dpi=GRAPH_DPI, bbox_inches="tight")
        print(f"그래프 저장: {out_path}")
    plt.show()
    plt.close()


def load_base_result():
    search_dir = setup_paths()
    set_korean_font()
    import project_base
    return project_base.run_base_pipeline(search_dir=search_dir)


def display_table(title, df):
    print(f"\n[{title}]")
    display(df)


# ============================================================
# 시각화 보정
# - 교통량 값의 차이가 작아 막대/선이 일자로 보이는 그래프는 y축 또는 x축을 확대한다.
# - 하단이 생략된 그래프에는 "차이 확대 축" 문구를 표시해서 해석할 때 헷갈리지 않게 한다.
# ============================================================

def _numeric_values(values):
    arr = pd.Series(np.ravel(values)).dropna().astype(float)
    arr = arr[np.isfinite(arr)]
    return arr


def _format_number_axis(ax, axis="y"):
    try:
        from matplotlib.ticker import FuncFormatter
        formatter = FuncFormatter(lambda x, pos: f"{x:,.0f}")
        if axis == "y":
            ax.yaxis.set_major_formatter(formatter)
        else:
            ax.xaxis.set_major_formatter(formatter)
    except Exception:
        pass


def apply_zoom_y(ax, values, lower_margin=0.35, upper_margin=0.65):
    arr = _numeric_values(values)
    if len(arr) == 0:
        return
    vmin = float(arr.min())
    vmax = float(arr.max())
    spread = vmax - vmin
    if spread <= 0:
        spread = max(abs(vmax) * 0.03, 1.0)
    y_min = vmin - spread * lower_margin
    y_max = vmax + spread * upper_margin
    if vmin >= 0:
        y_min = max(0, y_min)
    if y_max <= y_min:
        y_max = y_min + spread
    ax.set_ylim(y_min, y_max)
    _format_number_axis(ax, "y")



def apply_zoom_x(ax, values, lower_margin=0.35, upper_margin=0.90, note="차이 확대 x축"):
    arr = _numeric_values(values)
    if len(arr) == 0:
        return
    vmin = float(arr.min())
    vmax = float(arr.max())
    spread = vmax - vmin
    if spread <= 0:
        spread = max(abs(vmax) * 0.03, 1.0)
    x_min = vmin - spread * lower_margin
    x_max = vmax + spread * upper_margin
    if vmin >= 0:
        x_min = max(0, x_min)
    if x_max <= x_min:
        x_max = x_min + spread
    ax.set_xlim(x_min, x_max)
    _format_number_axis(ax, "x")
    if x_min > 0:
        ax.text(0.01, 0.02, note, transform=ax.transAxes, fontsize=9, color="dimgray", va="bottom")


def add_vertical_labels(ax, bars, values, fmt="{:,.0f}", fontsize=9):
    y_min, y_max = ax.get_ylim()
    offset = (y_max - y_min) * 0.025
    for bar, value in zip(bars, values):
        value = float(value)
        va = "bottom" if value >= 0 else "top"
        y = value + offset if value >= 0 else value - offset
        ax.text(bar.get_x() + bar.get_width() / 2, y, fmt.format(value), ha="center", va=va, fontsize=fontsize)


def add_horizontal_labels(ax, bars, values, fmt="{:,.0f}", fontsize=9):
    x_min, x_max = ax.get_xlim()
    offset = (x_max - x_min) * 0.02
    for bar, value in zip(bars, values):
        value = float(value)
        ax.text(value + offset, bar.get_y() + bar.get_height() / 2, fmt.format(value), va="center", fontsize=fontsize)

# ============================================================
# 승보: 요일별 교통량 예측
# 최종 출력 그래프: 10개
# 1) 2020~2025 실제 요일별 평균 교통량
# 2) 2020~2030 요일별 교통량 추이
# 3) 2020~2030 평일/주말 평균 추이
# 4~8) 2025 실제 vs 2026~2030 각 연도별 비교
# 9) 연도×요일 교통량 히트맵
# 10) 2025 대비 2030 요일별 변화율
# ============================================================

import project_base as pb

WEEKDAY_ORDER = ["월", "화", "수", "목", "금", "토", "일"]
ACTUAL_YEARS = list(range(2020, 2026))
PRED_YEARS = list(range(2026, 2031))
GROUP_COLS_MONTH = ["spot_num", "road_type", "io_type", "weekday_code"]
TARGET_COL = "vol_daily_avg"


def train_monthly_trend(df, group_cols, target_col):
    d = df.dropna(subset=[target_col]).copy()
    d[target_col] = pd.to_numeric(d[target_col], errors="coerce")
    d = d.dropna(subset=[target_col])
    for col in group_cols:
        d[col] = d[col].astype("string").fillna("미상")
    d["_x"] = ((d["year"] - 2020) * 12 + (d["month"] - 1)).astype(float)
    d["_y"] = d[target_col].astype(float)
    d["_xx"] = d["_x"] * d["_x"]
    d["_xy"] = d["_x"] * d["_y"]
    ag = d.groupby(group_cols, as_index=False, observed=True).agg(
        n=("_y", "count"), sx=("_x", "sum"), sy=("_y", "sum"), sxx=("_xx", "sum"), sxy=("_xy", "sum")
    )
    denom = (ag["n"] * ag["sxx"] - ag["sx"] * ag["sx"]).replace(0, np.nan)
    ag["slope"] = ((ag["n"] * ag["sxy"] - ag["sx"] * ag["sy"]) / denom).fillna(0.0)
    ag["intercept"] = (ag["sy"] - ag["slope"] * ag["sx"]) / ag["n"]
    line = ag[group_cols + ["slope", "intercept"]]
    dd = d.merge(line, on=group_cols, how="left")
    dd["resid"] = dd["_y"] - (dd["intercept"] + dd["slope"] * dd["_x"])
    seas = dd.groupby(group_cols + ["month"], as_index=False, observed=True)["resid"].mean().rename(columns={"resid": "season_adj"})
    return {"line": line, "season": seas, "group_cols": group_cols, "fallback": float(d["_y"].mean())}


def predict_monthly_trend(model, station_latest, target_year):
    group_cols = model["group_cols"]
    parts = []
    for month in range(1, 13):
        keys = pb.make_weekday_input(target_year, month, station_latest)
        k = keys.copy()
        for col in group_cols:
            k[col] = k[col].astype("string").fillna("미상")
        k["_x"] = float((target_year - 2020) * 12 + (month - 1))
        k = k.merge(model["line"], on=group_cols, how="left").merge(model["season"], on=group_cols + ["month"], how="left")
        pred = k["intercept"] + k["slope"] * k["_x"] + k["season_adj"].fillna(0.0)
        keys["pred_vol_daily_avg"] = pred.fillna(model["fallback"]).clip(lower=0).values
        parts.append(keys)
    return pd.concat(parts, ignore_index=True)


def build_tables(base_result):
    common_weekday = base_result["common_weekday"].copy()
    station_latest = base_result["station_latest"].copy()
    model = train_monthly_trend(common_weekday, GROUP_COLS_MONTH, TARGET_COL)
    pred_rows = []
    for year in PRED_YEARS:
        yp = predict_monthly_trend(model, station_latest, year)
        wk = yp.groupby("weekday_code", observed=True)["pred_vol_daily_avg"].mean().reindex(WEEKDAY_ORDER)
        pred_rows.append(wk.rename(year))
    pred_table = pd.concat(pred_rows, axis=1).T.reindex(columns=WEEKDAY_ORDER)
    actual_table = (
        common_weekday.groupby(["year", "weekday_code"], observed=True)["vol_daily_avg"]
        .mean().unstack("weekday_code").reindex(index=ACTUAL_YEARS, columns=WEEKDAY_ORDER)
    )
    full_table = pd.concat([actual_table, pred_table]).round(0)
    full_table.index.name = "연도"
    full_table.columns.name = "요일"
    return actual_table.round(0), full_table


def build_summary_table(full_table):
    summary = pd.DataFrame({
        "평일평균(월~금)": full_table[["월", "화", "수", "목", "금"]].mean(axis=1),
        "주말평균(토~일)": full_table[["토", "일"]].mean(axis=1),
    }).round(0)
    summary.index.name = "연도"
    return summary


def plot_actual_weekday_bar(actual_table):
    avg = actual_table.mean(axis=0).reindex(WEEKDAY_ORDER)
    ax = avg.plot(kind="bar", figsize=(9, 5), width=0.65)
    ax.set_title("2020~2025 실제 요일별 평균 교통량")
    ax.set_xlabel("요일")
    ax.set_ylabel("일평균 교통량")
    ax.tick_params(axis="x", rotation=0)
    ax.grid(axis="y", alpha=0.3)
    apply_zoom_y(ax, avg.values)
    for bar, value in zip(ax.patches, avg.values):
        ax.text(bar.get_x() + bar.get_width() / 2, value, f"{value:,.0f}", ha="center", va="bottom", fontsize=9)
    save_and_show("승보_01_실제_요일별_평균_교통량.png")


def plot_weekday_forecast_line(full_table):
    ax = plt.figure(figsize=(12, 6)).gca()
    for weekday in WEEKDAY_ORDER:
        ax.plot(full_table.index, full_table[weekday], marker="o", linewidth=2, label=weekday)
    apply_zoom_y(ax, full_table[WEEKDAY_ORDER].values)
    ax.axvline(2025.5, linestyle="--", alpha=0.7)
    ax.text(2025.55, ax.get_ylim()[1], "← 실제 | 예측 →", va="top", ha="left")
    ax.set_title("2020~2030 요일별 교통량 추이")
    ax.set_xlabel("연도")
    ax.set_ylabel("일평균 교통량")
    ax.set_xticks(full_table.index)
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend(title="요일", ncol=2)
    save_and_show("승보_02_요일별_교통량_추이_예측.png")


def plot_weekend_weekday_line(summary):
    ax = plt.figure(figsize=(11, 5.5)).gca()
    ax.plot(summary.index, summary["평일평균(월~금)"], marker="o", linewidth=2, label="평일평균(월~금)")
    ax.plot(summary.index, summary["주말평균(토~일)"], marker="s", linewidth=2, label="주말평균(토~일)")
    apply_zoom_y(ax, summary[["평일평균(월~금)", "주말평균(토~일)"]].values)
    ax.axvline(2025.5, linestyle="--", alpha=0.7)
    ax.text(2025.55, ax.get_ylim()[1], "← 실제 | 예측 →", va="top", ha="left")
    ax.set_title("2020~2030 평일/주말 평균 교통량 추이")
    ax.set_xlabel("연도")
    ax.set_ylabel("일평균 교통량")
    ax.set_xticks(summary.index)
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend()
    save_and_show("승보_03_평일_주말_평균_추이.png")


def plot_2025_vs_2030_bar(full_table):
    x = np.arange(len(WEEKDAY_ORDER))
    width = 0.38
    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.bar(x - width/2, full_table.loc[2025, WEEKDAY_ORDER], width, label="2025 실제")
    ax.bar(x + width/2, full_table.loc[2030, WEEKDAY_ORDER], width, label="2030 예측")
    ax.set_xticks(x)
    ax.set_xticklabels(WEEKDAY_ORDER)
    ax.set_title("요일별 교통량: 2025 실제 vs 2030 예측")
    ax.set_xlabel("요일")
    ax.set_ylabel("일평균 교통량")
    ax.grid(axis="y", alpha=0.3)
    apply_zoom_y(ax, full_table.loc[[2025, 2030], WEEKDAY_ORDER].values)
    ax.legend()
    save_and_show("승보_04_2025_2030_요일별_비교.png")



def plot_2025_vs_year_bar(full_table, target_year, seq):
    """2025 실제와 각 예측 연도를 별도 그래프로 비교한다."""
    x = np.arange(len(WEEKDAY_ORDER))
    width = 0.38
    ax = plt.figure(figsize=(10, 5.4)).gca()
    ax.bar(x - width/2, full_table.loc[2025, WEEKDAY_ORDER], width, label="2025 실제")
    ax.bar(x + width/2, full_table.loc[target_year, WEEKDAY_ORDER], width, label=f"{target_year} 예측")
    ax.set_xticks(x)
    ax.set_xticklabels(WEEKDAY_ORDER)
    ax.set_title(f"요일별 교통량: 2025 실제 vs {target_year} 예측")
    ax.set_xlabel("요일")
    ax.set_ylabel("일평균 교통량")
    ax.grid(axis="y", alpha=0.3)
    ax.legend()
    apply_zoom_y(ax, full_table.loc[[2025, target_year], WEEKDAY_ORDER].values)
    save_and_show(f"승보_{seq:02d}_2025_{target_year}_요일별_비교.png")


def plot_all_years_weekday_bar(full_table):
    """2025 실제 + 2026~2030 예측을 요일별 그룹 막대그래프 하나로 묶어서 비교한다."""
    years = [2025, 2026, 2027, 2028, 2029, 2030]
    x = np.arange(len(WEEKDAY_ORDER))
    n = len(years)
    total_width = 0.8
    width = total_width / n

    ax = plt.figure(figsize=(13, 6)).gca()
    for i, year in enumerate(years):
        offset = (i - (n - 1) / 2) * width
        label = f"{year} 실제" if year == 2025 else f"{year} 예측"
        ax.bar(x + offset, full_table.loc[year, WEEKDAY_ORDER], width, label=label)

    ax.set_xticks(x)
    ax.set_xticklabels(WEEKDAY_ORDER)
    ax.set_title("요일별 교통량: 2025 실제 vs 2026~2030 예측")
    ax.set_xlabel("요일")
    ax.set_ylabel("일평균 교통량")
    ax.grid(axis="y", alpha=0.3)
    apply_zoom_y(ax, full_table.loc[years, WEEKDAY_ORDER].values)
    ax.legend(title="연도", ncol=3)
    save_and_show("승보_04_2025_2030_요일별_통합비교.png")


def plot_year_weekday_heatmap(full_table):
    data = full_table[WEEKDAY_ORDER].values.astype(float)
    plt.figure(figsize=(8.5, 7))
    im = plt.imshow(data, aspect="auto")
    plt.colorbar(im, label="일평균 교통량")
    plt.xticks(np.arange(len(WEEKDAY_ORDER)), WEEKDAY_ORDER)
    plt.yticks(np.arange(len(full_table.index)), full_table.index)
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            plt.text(j, i, f"{data[i, j] / 1000:.0f}k", ha="center", va="center", fontsize=7)
    plt.title("연도×요일 교통량 히트맵")
    plt.xlabel("요일")
    plt.ylabel("연도")
    save_and_show("승보_09_연도_요일_히트맵.png")


def plot_change_rate_bar(full_table):
    change = ((full_table.loc[2030, WEEKDAY_ORDER] - full_table.loc[2025, WEEKDAY_ORDER]) / full_table.loc[2025, WEEKDAY_ORDER] * 100).round(2)
    ax = change.plot(kind="bar", figsize=(9, 5), width=0.65)
    ax.axhline(0, linewidth=1)
    ax.set_title("2025 대비 2030 요일별 교통량 변화율")
    ax.set_xlabel("요일")
    ax.set_ylabel("변화율(%)")
    ax.tick_params(axis="x", rotation=0)
    ax.grid(axis="y", alpha=0.3)
    apply_zoom_y(ax, change.values, lower_margin=0.45, upper_margin=0.75)
    for bar, value in zip(ax.patches, change.values):
        ax.text(bar.get_x() + bar.get_width()/2, value, f"{value:.1f}%", ha="center", va="bottom" if value >= 0 else "top", fontsize=9)
    save_and_show("승보_10_2025_2030_요일별_변화율.png")


def plot_actual_and_change_combo(actual_table, full_table):
    """요일별 실제 평균 교통량(막대) + 2025→2030 변화율(선)을 이중 축 하나로 병합한다."""
    avg = actual_table.mean(axis=0).reindex(WEEKDAY_ORDER)
    change = ((full_table.loc[2030, WEEKDAY_ORDER] - full_table.loc[2025, WEEKDAY_ORDER])
              / full_table.loc[2025, WEEKDAY_ORDER] * 100).round(2)
    x = np.arange(len(WEEKDAY_ORDER))

    bar_color = "#9DC3E6"    # 교통량 막대: 연한 파랑(위의 선이 잘 보이도록 톤 다운)
    line_color = "#C00000"   # 변화율 선: 진한 빨강(대비 강조)
    up_color = "#C00000"     # 증가(+) 라벨: 빨강
    down_color = "#1F5FBF"   # 감소(-) 라벨: 파랑

    fig, ax1 = plt.subplots(figsize=(11, 6))
    bars = ax1.bar(x, avg.values, width=0.55, color=bar_color,
                   edgecolor="#6A9BD1", linewidth=0.6, label="실제 평균 교통량(2020~2025)")
    apply_zoom_y(ax1, avg.values)
    ax1.set_ylabel("일평균 교통량")
    ax1.set_xticks(x)
    ax1.set_xticklabels(WEEKDAY_ORDER, fontsize=11)
    ax1.set_xlabel("요일")
    ax1.grid(axis="y", alpha=0.25)
    for bar, value in zip(bars, avg.values):
        ax1.text(bar.get_x() + bar.get_width() / 2, value, f"{value:,.0f}",
                 ha="center", va="bottom", fontsize=9, color="#333333")

    ax2 = ax1.twinx()
    ax2.axhline(0, color="gray", linewidth=1, alpha=0.6)
    ax2.plot(x, change.values, color=line_color, marker="o", markersize=8,
             linewidth=2.6, label="2025→2030 변화율(%)", zorder=5)
    ax2.set_ylabel("변화율(%)")
    ax2.set_ylim(change.values.min() - 4, change.values.max() + 5)

    for xi, value in zip(x, change.values):
        up = value >= 0
        ax2.annotate(f"{value:+.1f}%", xy=(xi, value),
                     xytext=(0, 12 if up else -16), textcoords="offset points",
                     ha="center", va="bottom" if up else "top",
                     fontsize=14, fontweight="bold",
                     color=up_color if up else down_color,
                     bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="none", alpha=0.85))

    h1, l1 = ax1.get_legend_handles_labels()
    h2, l2 = ax2.get_legend_handles_labels()
    ax1.legend(h1 + h2, l1 + l2, loc="upper left", fontsize=10)
    ax1.set_title("요일별 실제 교통량(막대) + 2025→2030 변화율(선)", fontsize=13)
    save_and_show("승보_11_실제교통량_변화율_통합.png")


def plot_forecast_change_heatmap(full_table):
    """2025 실제 대비 2026~2030 예측 변화율을 히트맵으로 보여준다.
    여러 요일 선그래프가 겹쳐 보이는 문제를 줄이기 위한 대체 그래프다.
    """
    rate = ((full_table.loc[PRED_YEARS, WEEKDAY_ORDER] - full_table.loc[2025, WEEKDAY_ORDER]) / full_table.loc[2025, WEEKDAY_ORDER] * 100).round(2)
    data = rate.values.astype(float)
    plt.figure(figsize=(9.8, 5.2))
    vmax = max(abs(np.nanmin(data)), abs(np.nanmax(data)))
    im = plt.imshow(data, aspect="auto", cmap="coolwarm", vmin=-vmax, vmax=vmax)
    plt.colorbar(im, label="2025 대비 변화율(%)")
    plt.xticks(np.arange(len(WEEKDAY_ORDER)), WEEKDAY_ORDER)
    plt.yticks(np.arange(len(PRED_YEARS)), PRED_YEARS)
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            plt.text(j, i, f"{data[i, j]:+.1f}%", ha="center", va="center", fontsize=8)
    plt.title("2025 대비 2026~2030 요일별 예측 변화율")
    plt.xlabel("요일")
    plt.ylabel("예측 연도")
    save_and_show("승보_02_2025대비_예측연도_요일별_변화율_히트맵.png")


def main():
    base_result = load_base_result()
    actual_table, full_table = build_tables(base_result)
    summary = build_summary_table(full_table)
    display_table("2020~2025 실제 요일별 평균", actual_table)
    display_table("2020~2030 요일별 교통량 표", full_table)
    display_table("2020~2030 평일/주말 평균", summary)
    plot_actual_weekday_bar(actual_table)
    # 사진1(실제 평균 교통량) + 사진10(2030 변화율) 병합본 추가
    plot_actual_and_change_combo(actual_table, full_table)
    # 7개 요일 선그래프는 선이 겹쳐 보일 수 있어 캡처용 메인은 변화율 히트맵으로 대체한다.
    plot_forecast_change_heatmap(full_table)
    plot_weekend_weekday_line(summary)

    # 04~08 개별 5장 → 6개 연도 통합 막대그래프 1장으로 병합
    plot_all_years_weekday_bar(full_table)

    plot_year_weekday_heatmap(full_table)
    plot_change_rate_bar(full_table)


if __name__ == "__main__":
    main()